### ISSUE TITLE
.gitignore Düzenlemeleri

### ISSUE THREAD

**Issue by hyperpostulate** [suckerman7/JavaRestAPI-Demo#10]
Mert selamlar,
Commitlerde, projenin çalıştırılması sırasında oluşan log dosyalarının da eklendiğini gördüm. Repository'lerde log dosyaları ve eğer bu projede kullandığımız gibi in-file bir veritabanı çözümü kullanıyorsak, veritabanı dosyaları bulunmamalı.

Bu tarz dosyaları commit'lerde exclude etmek için gitignore dosyasına ekleme yapmak gerekiyor. Örnek gitignore dosyası olarak https://github.com/hyperpostulate/customer-api/blob/master/.gitignore 'u kullanabilirsin.

Kolaylıklar,
Mesut ORMANLI

**Comment by suckerman7** [comment]
Tamamdır, .gitignore dosyasında düzenlemeler yaptım.

**Comment by hyperpostulate** [comment]
main branch'ına gitignore'un yeni hallini ekleyecek pr'ı açıp merge ettiğinde bu issue'yu kapatacağım

**Comment by hyperpostulate** [comment]
Eline sağlık Mert, action da başarılı bir şekilde çalıştı. Issue'yu kapatıyorum.
