### ISSUE TITLE
Servis Katmanı Geliştirmeleri

### ISSUE THREAD

**Issue by hyperpostulate** [suckerman7/JavaRestAPI-Demo#11]
Mert selamlar,
API projelerinde genel olarak, katmanlı mimari kullanmak bakımı yapılabilir [maintainable] bir ürün ortaya çıkarmak için elzem.
Dolayısıyla genellikle, controller -> service -> repository şeklinde bir yapı kurgulanır. Teknik mimari olarak MVC [model-view-controller] yapısını araştırabilirsin, hatta bunun için ayrı bir dökümantasyon issue'su açacağım.

Bu proje özelinde, controller katmanında /hello endpointine GET isteği atıldığında "Hello World, with Docker!" şeklinde yanıt dönen bir endpoint mevcut olduğunu görüyorum. Buradaki iş akışını servis katmanından alınacak hale getireceğiz.

Bunun için, "service" paketi altında HelloWorldService isminde bir interface oluşturup, bu interface'i HelloWorldServiceImpl isminde bir sınıfla extend edip, bu sınıfta "Hello World from service layer!" yanıtını dönecek bir method oluşturmanı istiyorum. Akabinde bu servisi controller katmanından çağıracaksın.

Örnek proje olarak https://github.com/hyperpostulate/customer-api/ 'daki yapıyı baz alabilirsin.

Veritabanında yaratacağımız tablo üzerinden okumaya yönelik geliştirmeyi de farklı bir issue üzerinden yapacağız.

Kolaylıklar,
Mesut ORMANLI

**Comment by suckerman7** [comment]
bunu da .gitignore gibi ayrı bir branch'de üstünde uğraşacağım.

**Comment by suckerman7** [comment]
Bunun üstünde başladım, araştırma yaptım ama daha tam işe koyulamadım. Ama en azından bunun için bir pull request açtım sizin de takip edebilmeniz için.

**Comment by hyperpostulate** [comment]
Eline sağlık Mert! :)
