### ISSUE TITLE
MVC Dökümantasyonu

### ISSUE THREAD

**Issue by hyperpostulate** [suckerman7/JavaRestAPI-Demo#12]
Selam Mert, 
https://github.com/suckerman7/JavaRestAPI-Demo/issues/11 'de bahsettiğim MVC mimarisi hakkında yine blog yazısı formatında bir döküman oluşturup, wiki altına eklemeni rica ediyorum.

Kolaylıklar,
Mesut ORMANLI

**Comment by suckerman7** [comment]
Mesut Bey iyi günler, dökümantasyonu hazırladım ve Wiki kısmına ekledim. Boş olduğunuz bir zaman göz atabilirsiniz. Bunu yazarken kullandığım kaynakları da referans kısmına ekledim.

**Comment by hyperpostulate** [comment]
Selamlar Mert, genel olarak ASP.NET platformuna dair bir perspektifle yazılmasına rağmen konsept hakkında genel olarak doyurucu bilgiler içeren bir yazı olmuş, eline sağlık! :)
