### ISSUE TITLE
Entity  ve Repository Tanımları

### ISSUE THREAD

**Issue by hyperpostulate** [suckerman7/JavaRestAPI-Demo#16]
Mert selamlar,
Uygulamanın REST endpoint'i üzerinden verdiği çıktılar şu anda doğrudan servis katmanından gelmekte. [HelloWorldService].
Bu issue kapsamında bu çıktıları veritabanından okutmaya yönelik geliştirmelerin ilk adımını atacaksın.  Nihai hedefimiz, REST API üzerinden alınan mesajları veritabanına kaydedip yine aynı API üzerinden veritabanından okuyabilen bir uygulama geliştirmek.

Öncelikle, entity sınıfını tanımlamak gerekecek. Yeni oluşturacağın model package'ı altındaki entity package'ı altında, "Message" isminde bir entity sınıfı oluşturmalısın. Bu sınıf, primary key olarak "id", diğer property'ler olarak messageTR ve messageEN alanlarını içermeli.

Daha sonrasında JPA kullanarak bu entity'i manuple edecek MessageRepository isminde bir repository _interface'i_ oluşturmalısın. Servis ve controller katmanındaki değişiklikleri yeni bir issue üzerinden gerçekleştireceğiz.

Service ve controller katmanlarındaki değişiklikleri tamamladığımızda, örn. {baseUrl}/message/1 adresine GET isteği atıldığında, veritabanından 1 id'li kaydın okunup, aşağıdaki çıktıyı görmemiz gerekiyor:

```
{
"id": 1,
"messageTR": "Merhaba Dünya!",
"messageEN": "Hello World!"
}
```

Ancak belirttiğim gibi bu issue kapsamında Entity ve Repository'i oluşturman yeterli olacak. Takıldığın noktalarda referans olarak yine customer-api projesine başvurabilirsin.

Kolaylıklar,
Mesut ORMANLI

**Comment by suckerman7** [comment]
Dökümantasyondan sonra bunun üzerinde uğraşmaya başlayacağım. Öncelikle bir branch açarak.
