### ISSUE TITLE
Clean Code Dökümantasyonu

### ISSUE THREAD

**Issue by hyperpostulate** [suckerman7/JavaRestAPI-Demo#17]
Mert selamlar,
Bu issue kapsamında, "clean code" kavramı hakkında araştırma yapmanı, bu kavramın neden önemli olduğuna dair blog yazısı formatında bir döküman oluşturarak wiki altına eklemeni istiyorum.

Döküman Türkçe olacak, bulabildiğin tüm kaynaklardan faydalanabilirsin. Ancak buradaki amaç sadece bir blog yazısı yazman değil, clean code'un önemini kavraman. Buna yönelik olarak bir sonraki ofis gününde konu hakkında sorular soracağım.

Kolaylıklar,
Mesut ORMANLI

**Comment by suckerman7** [comment]
Dökümantasyonu oluşturdum ve wiki kısmına ekledim. Yarına hazırlanmak için de okuyup üstünden geçeceğim.

**Comment by hyperpostulate** [comment]
Eline sağlık Mert!
