### ISSUE TITLE
Functional Programming Hakkında Araştırma

### ISSUE THREAD

**Issue by hyperpostulate** [suckerman7/JavaRestAPI-Demo#20]
Merhaba Mert,
Bu issue kapsamında Functional Programming hakkında araştırma yapmanı istiyorum. Araştırma fonksiyonel programlamanın tarihini, diğer programlama paradigmalarına nazaran avantajlarını ve dezavantajarını, ve modern programlama dillerindeki (örn. Java) uygulama alanlarını içermeli. Yaptığın araştırma sonuçlarını yine blog yazısı formatında wiki altına eklemelisin.

Kolaylıklar,
Mesut ORMANLI

**Comment by suckerman7** [comment]
Blog yazısı formatında Wiki altına ekledim.

**Comment by hyperpostulate** [comment]
Eline sağlık Mert!
