### ISSUE TITLE
Sonarlint

### ISSUE THREAD

**Issue by hyperpostulate** [suckerman7/JavaRestAPI-Demo#3]
Mert selamlar,
Özgür yazılım / açık kaynak dünyasında da, kurumsal yazılım geliştirme dünyasında da, tek bir developer'ın uçtan uca geliştirdiği projeler oldukça küçük bir azınlığa tekabül etmekte. Dolayısıyla projelerimizi bir yazılım geliştirme standardı üzerinde geliştirmek büyük önem arz ediyor.

Yazılım geliştirme standartlarını projeye katkıda bulunacak developer'lara "enforce" etmek için en efektif yollardan biri, statik kod analizi araçlarını kullanmak. Java özelinde en çok kullanılan statik kod analizi aracı da SonarLint.

SonarLint hakkında faydalanabileceğin bir kaynak: https://semihsaydam.medium.com/sonarqube-sonarlint-ff8c13f08c3e

Bu issue kapsamında, kullandığın IDE'ye SonarLint plug-inini kurmanı, akabinde de bu plug-in'in verdiği uyarıları çözmeni isteyeceğim.

SonarLint benim localimde mevcut, dolayısıyla ilk issue'yu kapattığında https://github.com/Suckerman7/JavaRestAPI-Demo/issues/1 ve proje localde ayağa kalkabildiğinde, projeyi analize tabi tutup, çıktılarını bu issue üzerinde comment olarak ekleyecek ve çözmeni bekleyeceğim.

Kolaylıklar,
Mesut ORMANLI

**Comment by suckerman7** [comment]
IDE olarak kullandığım Visual Studio'da SonarLint plugin'ini kurdum, ve plugin'in verdiği sample dosyasında SonarLint'in nasıl çalıştığını inceledim. Yapmam gereken başka bir şey var mı?

**Comment by hyperpostulate** [comment]
şu an için yok, analiz çalıştırıp akabinde -gerekli olursa- analizden çıkacak bulgulara yönelik yeni issue'lar açacağım.
