### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by hyperpostulate** [suckerman7/JavaRestAPI-Demo#4]
Mert merhaba,
Geliştirdiğimiz uygulamaları dockerize ederek bir docker container'ı üzerinde çalıştırmak, hem modern bir yaklaşım, hem de birçok artısı var: örneğin klasik "localimde çalışıyor" (it works on my machine) sorununu çözmek gibi.

Bu feature kapsamında, docker'ı araştırmanı, local'ine kurmanı, akabinde  https://github.com/Suckerman7/JavaRestAPI-Demo/issues/1 ve https://github.com/Suckerman7/JavaRestAPI-Demo/issues/3 tamamlandıktan sonra bu projeyi dockerize ederek docker üzerinde çalıştırmanı isteyeceğim.

Faydalı olacağını düşündüğüm linkleri aşağıda paylaşıyorum:

https://www.yusufsezer.com.tr/docker/

https://metinalniacik.medium.com/spring-boot-uygulamas%C4%B1n%C4%B1-docker-konteyner%C4%B1-haline-getirmek-bcf22a2f6d7

Not: linklerdeki açıklamalar eski ve/veya kullandığın bağımlılıklarla uyumsuz olabilir. Bu durumda biraz araştırma yapman gerekecek.

Kolaylıklar,
Mesut ORMANLI

**Comment by suckerman7** [comment]
Docker'ı localime kurdum ve uygulama içindeki örneklerle nasıl çalıştığını öğrendim.

**Comment by suckerman7** [comment]
Projeyi dockerize etmeye çalışıyorum, ama sürekli hata veriyor. IntelliJ'de Docker'a bağlanmaya çalışıyorum ama **Cannot connect to the Docker daemon at npipe:////./pipe/docker_engine. Is the docker daemon running?** diye bir hata veriyor.

onun yerine Komut İstemi'nde aynı şeyi deneyince **ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory** diye hata veriyor.

Projenin root'unda Dockerfile olmasına rağmen bu hataları verip duruyor.

**Comment by hyperpostulate** [comment]
selam Mert, lokaldeki docker deamon'ının ayağa kaldırılması konusunda 27 Mayıs Pazartesi günü ofise geldiğinde hatırlatırsın, beraber bakarız.

**Comment by suckerman7** [comment]
Bunun için de diğer yaptığımız tasklar gibi bir branch açacağım. Onun üzerinden daha kolay olur.
